#!/bin/bash

foamLog log.inter >/dev/null

gnplot -persist > /dev/null 2>&1 << EOF
       set logscale y
       set title "Residual Plot"
       set xlabel "Iteration"
       set ylabel "Residual"
       plot "logs/p_rgh" wih lines

EOF